CREATE TABLE IF NOT EXISTS [questions] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, [title] NVARCHAR NOT NULL, [question_type] INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS [answers] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, [question_id] INTEGER NOT NULL, [title] NVARCHAR NOT NULL, [is_correct] BOOLEAN NOT NULL CHECK (is_correct IN (0,1)));
CREATE TABLE IF NOT EXISTS [app_config] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, [password1] NVARCHAR NOT NULL, [password2] NVARCHAR NOT NULL);
CREATE TABLE IF NOT EXISTS [images] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, [name] NVARCHAR NOT NULL, [data] BLOB);
INSERT INTO [app_config] (password1, password2) VALUES ("exit","check"); 